#include "pch.h"
#include "Headers.h"
#include <iostream>
#include <string>

using namespace std;

// 3. Write a program reading regular expressions, then constructing NFA using Thompson algorithm, 
// converting NFA into DFA and checking if input strings are generated by this expression (working on DFA).

//ε - epsilon

int main()
{
	string RE;
    cout << "Please input RE:  ";		
	cin >> RE;

	checkRE(RE);					//Check if RE can be used to construct NFA

	cout << "Your input was " + RE;

	return 0;
}
